'use strict';
// Re-running an exercise. The seed, the starting state and the inputs are the
// whole exercise, so feeding them back in reproduces it exactly — and feeding
// them into a changed world (a working radio, no red cell) prices the fog.
//
// Only inputs from outside the engine are replayed. What the engine did on its
// own (the red cell, the drill director, a scripted inject) is regenerated by
// the rerun, not replayed, or it would happen twice.

const crypto = require('crypto');
const { Game } = require('./sim');
const { ProfileStore } = require('./profile');

const DT = 0.2;                 // the server's tick, in real seconds
const EXTERNAL = new Set(['trainee', 'instructor']);
const DECEPTIVE = new Set(['fake', 'forgedOrder', 'falseBda', 'spoof']);

// rec: a report (or anything with seed, scenario, cfg0, who0, profiles0, inputs, endT)
// overrides: { clearComms, noRedcell, noDeception } — each a different world
function rerun(rec, overrides = {}) {
  const cfg = { ...(rec.cfg0 || {}) };
  if (overrides.clearComms) Object.assign(cfg, { commsClear: true, ewEnabled: false, dropRate: 0, garbleRate: 0, delayMin: 0, delayMax: 0 });
  if (overrides.noRedcell) cfg.redcell = 'OFF';
  if (overrides.noDeception) cfg.noDeception = true;
  const scenarioId = rec.scenario && rec.scenario.id ? rec.scenario.id : rec.scenario;
  const g = new Game(scenarioId, cfg, { seed: rec.seed, who: rec.who0 || {}, profiles: ProfileStore.from(rec.profiles0) });

  const inputs = (rec.inputs || []).filter((i) => EXTERNAL.has(i.via));
  let next = 0, applied = 0, skipped = 0;
  const skippedList = [];
  const apply = (inp) => {
    const a = inp.a || {};
    // the world changed under these: the counterfactual says they never happen
    const absent = (overrides.noDeception && inp.via === 'instructor' && DECEPTIVE.has(a.type))
      || (overrides.noRedcell && inp.via === 'instructor' && a.type === 'redcell')
      || (overrides.clearComms && inp.via === 'instructor' && (a.type === 'link' || (a.type === 'emitter' && a.op !== 'remove')));
    if (absent) { skipped++; skippedList.push({ t: inp.t, via: inp.via, type: a.type, why: 'not part of this world' }); return; }
    const r = inp.via === 'trainee' ? g.action(inp.pid, a) : g.admin(a, 'instructor');
    // an input that failed the first time too is history repeating, not a casualty of the rerun
    if (r && r.error && inp.ok !== false) { skipped++; skippedList.push({ t: inp.t, via: inp.via, type: a.type, why: r.error }); }
    else applied++;
  };

  const endT = rec.endT != null ? rec.endT : Infinity;
  for (let guard = 0; guard < 400000; guard++) {
    while (next < inputs.length && inputs[next].t <= g.t + 1e-9) apply(inputs[next++]);
    if (g.status === 'ENDED') break;
    if (g.status !== 'RUNNING') {
      if (next >= inputs.length) break;            // nothing will ever start it again
      apply(inputs[next++]);                        // time stands still in the lobby or paused
      continue;
    }
    // a changed world can outlast the original (nobody died, say): stop where it stopped
    if (g.t >= endT - 1e-9) { g.end('Stopped where the original exercise ended'); break; }
    g.tick(DT);
  }
  if (g.status !== 'ENDED') g.end('Stopped where the original exercise ended');
  const { replay, ...aar } = g.aar;
  return { aar, game: g, applied, skipped, skippedList };
}

// A stable fingerprint of a report: sorted keys, numbers rounded past float
// noise, wall-clock times left out. Same exercise, same fingerprint.
const VOLATILE = new Set(['generatedAt', 'startedAt', 'at']);
function canonical(v) {
  if (v === null || typeof v !== 'object') {
    if (typeof v === 'number') return Number.isFinite(v) ? (Number.isInteger(v) ? v : Math.round(v * 1e6) / 1e6) : null;
    return v;
  }
  if (Array.isArray(v)) return v.map((x) => (x === undefined ? null : canonical(x)));
  const out = {};
  for (const k of Object.keys(v).sort()) {
    if (VOLATILE.has(k) || v[k] === undefined || typeof v[k] === 'function') continue;
    out[k] = canonical(v[k]);
  }
  return out;
}
// The replay frames are left out, as a rerun returns none; they are derived from the same state.
const fingerprint = (aar) => {
  const { replay, ...rest } = aar;
  return crypto.createHash('sha256').update(JSON.stringify(canonical(rest))).digest('hex');
};

module.exports = { rerun, canonical, fingerprint, DT };
